-- Create user if not exists
DO $$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles WHERE rolname = :'ADMIN_DB_USER'
   ) THEN
      EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER CREATEDB CREATEROLE INHERIT NOBYPASSRLS NOREPLICATION;', :'ADMIN_DB_USER', :'ADMIN_DB_PASSWORD');
   END IF;
END
$$;

-- Create database if not exists
DO $$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_database WHERE datname = :'ADMIN_DB_NAME'
   ) THEN
      EXECUTE format('CREATE DATABASE %I OWNER %I ENCODING ''UTF8'' TEMPLATE template0;', :'ADMIN_DB_NAME', :'ADMIN_DB_USER');
   END IF;
END
$$;

-- Grant permissions
GRANT CONNECT, CREATE ON DATABASE :"ADMIN_DB_NAME" TO :"ADMIN_DB_USER";