-- create :ADMIN_DB_USER user (only if does not exist)
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = :'ADMIN_DB_USER') THEN
        EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER CREATEDB CREATEROLE INHERIT NOBYPASSRLS NOREPLICATION', :'ADMIN_DB_USER', :'ADMIN_DB_PASSWORD');
    END IF;
END$$;

-- create database :ADMIN_DB_NAME (only if does not exist)
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_database WHERE datname = :'ADMIN_DB_NAME') THEN
        EXECUTE format('CREATE DATABASE %I OWNER %I ENCODING ''UTF8'' TEMPLATE template0', :'ADMIN_DB_NAME', :'ADMIN_DB_USER');
    END IF;
END$$;

-- grant permissions
GRANT CONNECT, CREATE ON DATABASE :"ADMIN_DB_NAME" TO :"ADMIN_DB_USER";

-- create :ADMIN_DB_NAME database
CREATE DATABASE :ADMIN_DB_NAME OWNER :ADMIN_DB_USER ENCODING 'UTF8' TEMPLATE template0;

-- grant permissions to :ADMIN_DB_USER
GRANT CONNECT,
CREATE ON DATABASE :ADMIN_DB_NAME TO :ADMIN_DB_USER;